### ISSUE TITLE
[gi branch] Some encoding issues left

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#192]
In the current exaile 4.0 (gi) branch, [encoding tracebacks](https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-%28GTK3-GStreamer-1.x%29#encoding-issues) should be fixed, but they are not (completely).
This happens when adding ordinary files to a playlist (from library or files panel):
```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1491, in _load_data_thread
    render_data = self._load_data_fn(coltypes, formatters, tracks)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1501, in _load_data_fn
    track_data = [track, self.icon_for_row(position).pixbuf] + [formatter(track) for formatter in formatters]
  File "/path/to/exaile/xl/formatter.py", line 402, in format
    substitute = track.get_tag_display(tag)
  File "/path/to/exaile/xl/trax/track.py", line 632, in get_tag_display
    value = unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 8: ordinal not in range(128)
```
and
```
ERROR   : Event callback exception caught!
Traceback (most recent call last):
  File "/path/to/exaile/xl/event.py", line 329, in _emit
    event.data, *cb.args, **cb.kwargs)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1405, in on_tracks_added
    self._load_data(tracks)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1486, in _load_data
    render_data = self._load_data_fn(coltypes, formatters, tracks)
  File "/path/to/exaile/xlgui/widgets/playlist.py", line 1501, in _load_data_fn
    track_data = [track, self.icon_for_row(position).pixbuf] + [formatter(track) for formatter in formatters]
  File "/path/to/exaile/xl/formatter.py", line 402, in format
    substitute = track.get_tag_display(tag)
  File "/path/to/exaile/xl/trax/track.py", line 632, in get_tag_display
    value = unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)
```

If you are interested I am willing to send you some affected files but I won't upload them here due to copyright.

**Comment by sjohannes** [comment]
Could you add a `print(tag, repr(value))` above that last line and post the output?

**Comment by genodeftest** [comment]
Every time I do this, the playlist is gone i.e. displays "loading" forever and can't be used any more.

Some examples:
* `('__basename', "'01 - K\\xc3\\xb6nigsfanfare.flac'")` (should be `01 - Königsfanfare.flac`) results in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)`
* `('__basename', "'02 - \\xe2\\x80\\x9eLobe den Herren\\xe2\\x80\\x9d.flac'")` should be `02 - „Lobe den Herren“.flac` results in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 5: ordinal not in range(128)`
* `('__basename', '\'09 - Symphony No. 6 in F major, Op. 68 "Pastorale": V. Allegretto. Frohe und dankbare Gef\\xc3\\xbchle nach dem Sturm.flac\'')` should contain `Gefühle`, resulting in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 89: ordinal not in range(128)`
* `('__basename', "'02 - Ebud\\xc3\\xa6.flac'")` should be `02 - Ebudæ.flac`, resulting in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)`
* `('__basename', "'\\xd0\\x93\\xd0\\xb5\\xd0\\xbe\\xd1\\x80\\xd0\\xb3\\xd0\\xb8\\xd0\\xb9 \\xd0\\xa1\\xd0\\xb2\\xd0\\xb8\\xd1\\x80\\xd0\\xb8\\xd0\\xb4\\xd0\\xbe\\xd0\\xb2 \\xe2\\x80\\x93 \\xd0\\x92\\xd1\\x80\\xd0\\xb5\\xd0\\xbc\\xd1\\x8f, \\xd0\\xb2\\xd0\\xbf\\xd0\\xb5\\xd1\\x80\\xd1\\x91\\xd0\\xb4!.ogg'")` should be `Георгий Свиридов – Время, вперёд!.ogg`, resulting in `UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

I guess that's enough for now. I'm on a Fedora 23 Linux, filesystem is btrfs/ext4, so filenames should already be unicode (UTF-8 according to `locale`). Files and Library panel are displaying file names just fine. I can even show and edit track properties without issues from there.

**Comment by sjohannes** [comment]
Thanks; I forgot that `__basename` is stored in raw bytes instead of unicode. The first commit should fix this by properly converting it to unicode. The second commit ensures that any similar bug does not cause an exception (rather it should just print a warning and try to recover).

**Comment by genodeftest** [comment]
Fix confirmed. Thank you very much!

**Comment by genodeftest** [comment]
There is one downside though: In playlists, column `filename` are now displayed with some characters unnecessarily escaped.  This includes:
* spaces become `%20`
* `æ` becomes `%C3%A6`
* Umlauts get replaced
* russian (and other non-ASCII) characters get completely replaced, leaving the `filename` column useless

Files panel is still correct. Track properties dialog still shows correct path too.

**Comment by sjohannes** [comment]
Ah yep; apparently `filename_display_basename` expects a file path, not URI. Should be fixed now.

**Comment by genodeftest** [comment]
Ok, now line break characters in titles (tags) make multi-line file titles. I think this is no issue. Thanks again!
