### ISSUE TITLE
Reduce logging: stop warning for glib.source_remove(self._redraw_timer)

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#24]
When reading files into the music library exaile does massive logging to console. I get tens of thousands of these messages with increasing source id:
~~~
exaile/xlgui/widgets/playlist.py:1337: Warning: Source ID 1046997 was not found when attempting to remove it
  glib.source_remove(self._redraw_timer)
~~~
It seems like https://github.com/exaile/exaile/blob/master/xlgui/widgets/playlist.py#L1337 wants to remove files from my playlist that aren't in it (since I closed all playlists before importing to music library).
Since this does not directly go to the logger via logger.event or something similar, would it be possible to check whether the source ID is not used any more and not remove it in this case?

**Comment by virtuald** [comment]
Interesting, I do not get any of these messages at startup, so I can't test this. Any special settings? 

I theorize that you could add a `self.redraw_timer = None` to the line directly after, and they would go away. Could you try that and see if your messages go away?

**Comment by genodeftest** [comment]
This does not happen at startup. It happens when scanning files/folders to import them into the library.
I'll try that.

**Comment by genodeftest** [comment]
Do you mean `self._redraw_timer = None` (with trailing underscore) ? What effect would that have? This will be overridden in line 1779 by `self._redraw_timer = glib.timeout_add(100, self._on_track_tags_changed)`. Adding the line (inside the if clause) didn't change anything and I don't understand what it should change.

The same thing happens for many different things like pressing the "next" button (sometimes, don't know when). It also happens when dragging a song from file browser into a playlist. This also affects line 634 in xlgui/panel/playlists.py.

**Comment by virtuald** [comment]
Oh, ha. You're right. Was hoping for a quick fix on it... I still cannot reproduce it in the other instances you're mentioning.

In both instances, it appears that it's not possible for... oh. Interesting. Which version of GTK are you using?

I'm guessing this is a threading issue. The only way this thing gets called is via `event.add_callback`, which if I remember correctly can sometimes (always?) call its callbacks from another thread. It's a nasty problem I've been contemplating dealing with for awhile. The only other place that `on_track_tags_changed` gets called from is `playlist.py:1219`, which is via `event.add_callback`.

You might try adding the xl.common.idle_add decorator to `on_track_tags_changed`, and see if that fixes it.

**Comment by genodeftest** [comment]
I am using gtk2 2.24.25.
I will try once I understand that far. Might take a while.

**Comment by virtuald** [comment]
I pushed code to this branch, try it out: https://github.com/virtuald/exaile/tree/decorator

**Comment by genodeftest** [comment]
Thanks, your change in https://github.com/virtuald/exaile/commit/effd560acdb3af723708adf80780533a467b0d4a removes the first of those warnings. The second one in xlgui/panel/playlists.py:634 still persists.

**Comment by genodeftest** [comment]
When scanning folder to import them into the library I found another point in code this warning is printed:
~~~
xl/common.py:224: Warning: Source ID 37189 was not found when attempting to remove it
  if id[0]: glib.source_remove(id[0])
~~~

**Comment by virtuald** [comment]
FYI: I get this message now. Must have been something that got updated?

**Comment by virtuald** [comment]
The way to reproduce this error message is just to change the tag of some file that happens to be showing in the current playlist, while Exaile isn't running. When it starts up, the error message shows up.

It turns out, this is actually a race condition because of a threading-related issue (see #83). I'll have a fix shortly.
